[tool.poetry]
name = "pntvcontrol"
version = "0.1.0"
description = "Controle de OS Terceiros"
authors = ["Thiago <tgpauluk@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"
waitress = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
